const USER_REGISTERATION = {
    USER_REGISTERATION_INIT: "USER_REGISTERATION_INIT",
    USER_REGISTERATION_SUCCESS: "USER_REGISTERATION_SUCCESS",
    USER_REGISTERATION_ERROR:"USER_REGISTERATION_ERROR"
}

const REQUEST_USER = {
    REQUEST_USER_INIT: "REQUEST_USER_INIT",
    REQUEST_USER_SUCCESS: "REQUEST_USER_SUCCESS",
    REQUEST_USER_ERROR:"REQUEST_USER_ERROR"
}

const USER_LOGIN = {
    USER_LOGIN_INIT: "USER_LOGIN_INIT",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_ERROR:"USER_LOGIN_ERROR"
}

const GET_CATEGORY = {
    GET_CATEGORY_INIT: "GET_CATEGORY_INIT",
    GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
    GET_CATEGORY_ERROR:"GET_CATEGORY_ERROR"
}

const ADD_CATEGORY = {
    ADD_CATEGORY_INIT: "ADD_CATEGORY_INIT",
    ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
    ADD_CATEGORY_ERROR:"ADD_CATEGORY_ERROR"
}

const UPDATE_CATEGORY = {
    UPDATE_CATEGORY_INIT: "UPDATE_CATEGORY_INIT",
    UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
    UPDATE_CATEGORY_ERROR:"UPDATE_CATEGORY_ERROR"
}

const DELETE_CATEGORY = {
    DELETE_CATEGORY_INIT: "DELETE_CATEGORY_INIT",
    DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
    DELETE_CATEGORY_ERROR:"DELETE_CATEGORY_ERROR"
}

export  {
    USER_REGISTERATION,
    REQUEST_USER,
    USER_LOGIN,
    GET_CATEGORY,
    ADD_CATEGORY,
    UPDATE_CATEGORY,
    DELETE_CATEGORY
}